/*
 * OffBlock API
 * OffBlock description of API.
 *
 * OpenAPI spec version: API TOS
 * Contact: myeaddress@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.offblocks.api;

import com.sphereon.sdk.offblocks.handler.ApiException;
import com.sphereon.sdk.offblocks.model.LoginRequest;
import com.sphereon.sdk.offblocks.model.SignUpRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthControllerApi
 */
@Ignore
public class AuthControllerApiTest {

    private final AuthControllerApi api = new AuthControllerApi();

    
    /**
     * authenticateUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authenticateUserUsingPOSTTest() throws ApiException {
        LoginRequest loginRequest = null;
        Object response = api.authenticateUserUsingPOST(loginRequest);

        // TODO: test validations
    }
    
    /**
     * registerUser
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void registerUserUsingPOSTTest() throws ApiException {
        SignUpRequest signUpRequest = null;
        Object response = api.registerUserUsingPOST(signUpRequest);

        // TODO: test validations
    }
    
}
