/*
 * OffBlock API
 * OffBlock description of API.
 *
 * OpenAPI spec version: API TOS
 * Contact: myeaddress@company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.offblocks.api;

import com.sphereon.sdk.offblocks.handler.ApiException;
import java.io.File;
import com.sphereon.sdk.offblocks.model.FileDTO;
import com.sphereon.sdk.offblocks.model.FileDetailsDTO;
import com.sphereon.sdk.offblocks.model.FileSignatoryDTO;
import com.sphereon.sdk.offblocks.model.Resource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FileControllerApi
 */
@Ignore
public class FileControllerApiTest {

    private final FileControllerApi api = new FileControllerApi();

    
    /**
     * createFile
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFileUsingPOSTTest() throws ApiException {
        String data = null;
        File file = null;
        FileDTO response = api.createFileUsingPOST(data, file);

        // TODO: test validations
    }
    
    /**
     * downloadOutputFile
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void downloadOutputFileUsingGETTest() throws ApiException {
        String fileId = null;
        Resource response = api.downloadOutputFileUsingGET(fileId);

        // TODO: test validations
    }
    
    /**
     * fileSignatoryProcess
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void fileSignatoryProcessUsingPOSTTest() throws ApiException {
        FileSignatoryDTO fileSignatoryDTO = null;
        List<FileDetailsDTO> response = api.fileSignatoryProcessUsingPOST(fileSignatoryDTO);

        // TODO: test validations
    }
    
    /**
     * getFileDetails
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFileDetailsUsingGETTest() throws ApiException {
        String id = null;
        List<FileDetailsDTO> response = api.getFileDetailsUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * getFileHistory
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFileHistoryUsingGETTest() throws ApiException {
        String id = null;
        List<FileDetailsDTO> response = api.getFileHistoryUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * getUndersignedFiles
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUndersignedFilesUsingGETTest() throws ApiException {
        Boolean isProcessed = null;
        List<FileDetailsDTO> response = api.getUndersignedFilesUsingGET(isProcessed);

        // TODO: test validations
    }
    
}
